# Generated by Django 4.0.3 on 2023-09-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('content', models.TextField()),
                ('date_mail', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_mail',),
            },
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date_post',),
            },
        ),
    ]
