# Generated by Django 5.0.2 on 2024-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmodel_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostWorksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_post', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Çalışmalar',
                'ordering': ('-date_post',),
            },
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'ordering': ('-date_mail',), 'verbose_name_plural': 'İletişim Talepleri'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-date_post',), 'verbose_name_plural': 'Makaleler'},
        ),
    ]
